FROM python:3.10-slim

WORKDIR /app

# Copia os arquivos do servidor
COPY server/ ./server/

# (Opcional) Se você tiver um requirements.txt com libs tipo Flask, Paho-MQTT, etc.
# COPY requirements.txt .
# RUN pip install -r requirements.txt

# Executa o servidor
CMD ["python", "server/server.py"]  